In [120]:
import os
import numpy as np  # linear algebra
import pandas as pd  #
from datetime import datetime
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import RidgeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
import lightgbm as lgb
from sklearn.metrics import confusion_matrix
%matplotlib inline

np.random.seed(7)

In [121]:
cols_remove = ['hours_worked_each_week', 'full_name']

In [204]:
train = pd.read_csv('train.csv')
train.drop(cols_remove, axis = 1, inplace = True)
y = train.infected  #.reset_index(drop=True)
features = train.drop(['infected'], axis=1)
features.head()

,gender,year_of_birth,weight,height,eye_color,race,accommodation_type,education_status,blood_type,family_members_count,...,owned_car_brand,owns_a_pet,has_health_insurance,has_cancer,smokes,has_alzheimers,facial_hair,daily_household_water_usage,diet_type,fast_food_meals_per_month
0,male,2024,8.69,52.32,brown,black,apartment,not_applicable,A+,4,...,none,no,no,no,no,no,none,1471.95,regular,2
1,male,1956,93.21,157.04,brown,asian,villa,associate_degree,AB+,5,...,none,no,no,no,no,no,short,1969.39,regular,0
2,male,1949,83.79,187.70,brown,white,apartment,associate_degree,B+,1,...,other,yes,no,no,no,yes,none,366.43,regular,16
3,female,1992,90.29,159.20,brown,middle_eastern,apartment,high_school,O+,5,...,honda,yes,yes,no,no,no,none,1548.20,regular,1
4,male,2013,40.23,96.61,brown,asian,apartment,not_applicable,O-,1,...,none,yes,yes,no,no,no,long,361.75,regular,12

In [205]:
num_cols = train._get_numeric_data().columns
num_cols = [x for x in num_cols if x != 'infected' and x != 'fast_food_meals_per_month']
print("Number of numerical fields:", len(num_cols))
num_cols

Number of numerical fields: 6

['year_of_birth',
 'weight',
 'height',
 'family_members_count',
 'avg_sleep_hours',
 'daily_household_water_usage']

In [206]:
cat_cols = train.select_dtypes(include=['object']).columns
print("Number of categorical fields:", len(cat_cols))
cat_cols

Number of categorical fields: 19

Index(['gender', 'eye_color', 'race', 'accommodation_type', 'education_status',
       'blood_type', 'occupation', 'living_area', 'sports_engagement',
       'favorite_music_genre', 'favorite_color', 'owned_car_brand',
       'owns_a_pet', 'has_health_insurance', 'has_cancer', 'smokes',
       'has_alzheimers', 'facial_hair', 'diet_type'],
      dtype='object')

In [216]:
cat2 = ['has_cancer', 'smokes', 'has_alzheimers', 'facial_hair', 'diet_type']

In [217]:
def expanding_mean(df_test, col):
    cumsum   = train.groupby(col)['infected'].cumsum() - train['infected']
    cumcnt = df_test.groupby(col).cumcount()
    df_test[col + '_mean'] = cumsum/cumcnt
    df_test[col + '_mean'] = df_test[col + '_mean'].replace([np.inf, -np.inf], np.nan)
    df_test[col + '_mean'].fillna(0.3343, inplace=True)
    return df_test

for col in cat2:
    features = expanding_mean(features, col)

features.head()

,gender,year_of_birth,weight,height,eye_color,race,accommodation_type,education_status,blood_type,family_members_count,...,facial_hair,daily_household_water_usage,diet_type,fast_food_meals_per_month,has_cancer_mean,smokes_mean,has_alzheimers_mean,facial_hair_mean,diet_type_mean,owned_car_brand_mean
0,male,1.606812,-2.234327,-2.266887,brown,black,apartment,not_applicable,A+,-0.408602,...,none,-0.294115,regular,2,0.3343,0.3343,0.334300,0.3343,0.3343,0.3343
1,male,-1.277283,1.039737,0.115224,brown,asian,villa,associate_degree,AB+,-0.081557,...,short,0.169637,regular,0,0.0000,0.0000,0.000000,0.3343,0.0000,0.0000
2,male,-1.574175,0.674833,0.812660,brown,white,apartment,associate_degree,B+,-1.389736,...,none,-1.324764,regular,16,0.0000,0.0000,0.334300,0.0000,0.0000,0.3343
3,female,0.249591,0.926625,0.164358,brown,middle_eastern,apartment,high_school,O+,-0.081557,...,none,-0.223029,regular,1,0.0000,0.0000,0.000000,0.0000,0.0000,0.3343
4,male,1.140267,-1.012557,-1.259403,brown,asian,apartment,not_applicable,O-,-1.389736,...,long,-1.329127,regular,12,0.2500,0.2500,0.333333,0.3343,0.2500,0.0000

In [218]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
features[num_cols] =  ss.fit_transform(features[num_cols])
features.head()

,gender,year_of_birth,weight,height,eye_color,race,accommodation_type,education_status,blood_type,family_members_count,...,facial_hair,daily_household_water_usage,diet_type,fast_food_meals_per_month,has_cancer_mean,smokes_mean,has_alzheimers_mean,facial_hair_mean,diet_type_mean,owned_car_brand_mean
0,male,1.606812,-2.234327,-2.266887,brown,black,apartment,not_applicable,A+,-0.408602,...,none,-0.294115,regular,2,0.3343,0.3343,0.334300,0.3343,0.3343,0.3343
1,male,-1.277283,1.039737,0.115224,brown,asian,villa,associate_degree,AB+,-0.081557,...,short,0.169637,regular,0,0.0000,0.0000,0.000000,0.3343,0.0000,0.0000
2,male,-1.574175,0.674833,0.812660,brown,white,apartment,associate_degree,B+,-1.389736,...,none,-1.324764,regular,16,0.0000,0.0000,0.334300,0.0000,0.0000,0.3343
3,female,0.249591,0.926625,0.164358,brown,middle_eastern,apartment,high_school,O+,-0.081557,...,none,-0.223029,regular,1,0.0000,0.0000,0.000000,0.0000,0.0000,0.3343
4,male,1.140267,-1.012557,-1.259403,brown,asian,apartment,not_applicable,O-,-1.389736,...,long,-1.329127,regular,12,0.2500,0.2500,0.333333,0.3343,0.2500,0.0000

In [219]:
X = pd.get_dummies(features)

In [220]:
X.head()

,year_of_birth,weight,height,family_members_count,avg_sleep_hours,daily_household_water_usage,fast_food_meals_per_month,has_cancer_mean,smokes_mean,has_alzheimers_mean,...,has_alzheimers_yes,facial_hair_long,facial_hair_none,facial_hair_short,diet_type_keto,diet_type_low-carb,diet_type_paleo,diet_type_regular,diet_type_vegan,diet_type_vegetarian
0,1.606812,-2.234327,-2.266887,-0.408602,1.896597,-0.294115,2,0.3343,0.3343,0.334300,...,0,0,1,0,0,0,0,1,0,0
1,-1.277283,1.039737,0.115224,-0.081557,-1.455885,0.169637,0,0.0000,0.0000,0.000000,...,0,0,0,1,0,0,0,1,0,0
2,-1.574175,0.674833,0.812660,-1.389736,-0.338391,-1.324764,16,0.0000,0.0000,0.334300,...,1,0,1,0,0,0,0,1,0,0
3,0.249591,0.926625,0.164358,-0.081557,0.220356,-0.223029,1,0.0000,0.0000,0.000000,...,0,0,1,0,0,0,0,1,0,0
4,1.140267,-1.012557,-1.259403,-1.389736,0.220356,-1.329127,12,0.2500,0.2500,0.333333,...,0,1,0,0,0,0,0,1,0,0

In [221]:
X_train, X_valid, y_train, y_valid = train_test_split(X,y,train_size=0.70,test_size=0.30,random_state=0)#Results dataframe
cols = ['Case','SGD','Ridge','KNN','SVM','Bagging','RndForest','LogReg','LGB']
resul = pd.DataFrame(columns=cols)
resul.set_index("Case",inplace=True)
resul.loc['Standard'] = [0,0,0,0,0,0,0,0]
resul.loc['GridSearch'] = [0,0,0,0,0,0,0,0]
resul.loc['RandomSearch'] = [0,0,0,0,0,0,0,0]
resul.loc['Hyperopt'] = [0,0,0,0,0,0,0,0]

In [ ]:
#Models creation
sgd   = SGDClassifier()
ridge = RidgeClassifier()
knn   = KNeighborsClassifier()
svc   = SVC(gamma='auto')
bag   = BaggingClassifier()
rf    = RandomForestClassifier(n_estimators=10)
lr    =  LogisticRegression(solver='liblinear')
lgg   = lgb.LGBMClassifier()

models = [sgd,ridge,knn,svc,bag,rf,lr,lgg]

col = 0
for model in models:
    model.fit(X_train,y_train.values.ravel())
    resul.iloc[0,col] = model.score(X_valid,y_valid)
    col += 1
    
resul.head()

In [214]:
sgd   = SGDClassifier()
ridge = RidgeClassifier()
knn   = KNeighborsClassifier()
svc   = SVC(gamma='auto')
bag   = BaggingClassifier()
rf    = RandomForestClassifier(n_estimators=10)
lr    =  LogisticRegression(solver='liblinear')
lgg   = lgb.LGBMClassifier()

In [215]:
from sklearn.ensemble import VotingClassifier
voting_clf = VotingClassifier(estimators=[('ridge', ridge), ('LGBM', lgg), ('LogReg', lr)], voting='hard')
voting_clf.fit(X_train, y_train)
preds = voting_clf.predict(X_valid)
accuracy_score(y_valid, preds)

0.7504166666666666

In [ ]:
sgd   = SGDClassifier()
ridge = RidgeClassifier()
knn   = KNeighborsClassifier()
svc   = SVC(gamma='auto')
bag   = BaggingClassifier()
rf    = RandomForestClassifier(n_estimators=10)
lr    =  LogisticRegression(solver='liblinear')
lgg   = lgb.LGBMClassifier()

In [195]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedStratifiedKFold

#Ridge
alpha = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
ridge_grid = dict(alpha=alpha)#K-Nearest - Neighborg
n_neighbors = range(1, 21, 2)
weights = ['uniform', 'distance']
metric = ['euclidean', 'manhattan', 'minkowski']
knn_grid = dict(n_neighbors=n_neighbors,weights=weights,metric=metric)

#Logistic Regrresion
solvers = [ 'liblinear']
penalty = ['l2', 'l1']
c_values = [100, 10, 1.0, 0.1, 0.01]
lr_grid = dict(solver=solvers,penalty=penalty,C=c_values)

#LGB
class_weight = [None,'balanced']
boosting_type = ['gbdt', 'goss', 'dart']
num_leaves = [30,50,100,150] #list(range(30, 150)),
learning_rate = list(np.logspace(np.log(0.005), np.log(0.2), base = np.exp(1), num = 10)) #1000
lgg_grid = dict(class_weight=class_weight, boosting_type=boosting_type, num_leaves=num_leaves, learning_rate =learning_rate)

models = [sgd,ridge,knn,svc,bag,rf,lr,lgg]
grids = [sgd_grid,ridge_grid,knn_grid,svc_grid,bag_grid,rf_grid,lr_grid,lgg_grid]

col = 0
for ind in range(0,len(models)):
    cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, 
                                 random_state=1)    
    grid_search = GridSearchCV(estimator=models[col], 
                  param_grid=grids[col], n_jobs=2, 
#                   cv = cv,
                  scoring='accuracy',error_score=0)    

    grid_clf_acc = grid_search.fit(X_train, y_train)
    resul.iloc[1,col] = grid_clf_acc.score(X_valid,y_valid)
    col += 1
    
resul.head()

In [196]:
from sklearn.metrics import accuracy_score
lr    =  LogisticRegression(solver='liblinear')
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3,  
                             random_state=1)
n_iter_search = 3
grid_search = GridSearchCV(estimator=lr, param_grid=lr_grid, 
              n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_win = grid_search.fit(X_train, y_train)

#Predict values based on new parameters
yv_pred = grid_win.predict(X_valid)

print(accuracy_score(y_valid, yv_pred))

0.7479166666666667

In [80]:
test = pd.read_csv('test.csv')
test.drop(cols_remove, axis = 1, inplace = True)
Xtest = pd.get_dummies(test)

In [81]:
def save_df(y_pred):
    out_df=pd.DataFrame(y_pred, columns= ['prediction'])
    out_df.index.names = ['id']
    out_df.index += 1 
    out_df.to_csv('out.csv')

In [82]:
yt_pred = grid_win.predict(Xtest)

In [83]:
save_df(yt_pred)